import { Box, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import CurrentlyReadingContainer from '../components/CurrentlyReadingContainer';
import NewBooksContainer from '../components/NewBooksContainer';
import ReviewsOfTheDayContainer from '../components/ReviewsOfTheDayContainer';
import SearchBox from '../components/SearchBox';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="#FFF6E5" w="100%" h="100%" p="50px 20px 0 20px">
        <SearchBox />

        <Box mt="30" display="flex" alignItems="center">
          <Heading color="#55565A">Hi,</Heading>
          <Heading ml="2" color="#FE6A78">
            Foton Dev Team 👋🏽
          </Heading>
        </Box>
        <NewBooksContainer />
        <CurrentlyReadingContainer />
        <ReviewsOfTheDayContainer />
      </Box>
    </div>
  );
};

export default Home;
