import { Box } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import SearchBox from '../components/SearchBox';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="#FFF6E5" w="100%" h="100vh" p="50px 20px 0 20px">
        <SearchBox />
      </Box>
    </div>
  );
};

export default Home;
