import { Box, Heading } from '@chakra-ui/react';
import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import CurrentlyReadingContainer from '../components/CurrentlyReadingContainer';
import NewBooksContainer from '../components/NewBooksContainer';
import ReviewsOfTheDayContainer from '../components/ReviewsOfTheDayContainer';
import SearchBox from '../components/SearchBar';
import { GetStaticProps } from 'next';

type Books = {
  title: string;
  author: string;
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch(
    'https://www.googleapis.com/books/v1/volumes?q=the%20name%20of%20the%20wind=lite'
  );
  const books: Books[] = await res.json();
  console.log(books);

  return {
    props: {
      books,
    },
  };
};

const Home: NextPage = ({
  books,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="#FFF6E5" w="100%" h="100%" p="50px 20px 0 20px">
        <SearchBox />

        <Box mt="30" display="flex" alignItems="center">
          <Heading color="#55565A">Hi,</Heading>
          <Heading ml="2" color="#FE6A78">
            Foton Dev Team 👋🏽
          </Heading>
        </Box>
        <NewBooksContainer />
        <CurrentlyReadingContainer />
        <ReviewsOfTheDayContainer />
      </Box>
    </div>
  );
};

export default Home;
